### ISSUE TITLE
Button for starting combat sometimes opens inventory instead

### ISSUE THREAD

**Issue by Tritrinai** [Innoxia/liliths-throne-public#1046]
3.0.5., besides some fights in alleys and tunnels it happened every time I tried to fight Dark Siren's lieutenants.

**Comment by arpie-steele** [comment]
I think this is related:

I found a game-altering bug in 0.3.0.7, and traced to current code on the dev branch.

Division by zero bug: "int size = Math.min(50, (100/exposedAreas+1));" in getExposedStatus() method of game/character/effects/StatusEffect.

How seen: Soon after loading a save, I was ambushed in the harpy nest. The Fight button resulted in a division by zero with full stack trace dumped to error log and dumped me into inventory screen, but not a good one which I could close and continue on my way.

Presumably opponent was mostly dressed but  had (or had clothing with) StatusEffect.EXPOSED_BREASTS and getExposedStatus didn't notice any exposed skin because either owner.hasBreasts() was false or owner.isCoverableAreaVisible(CoverableArea.NIPPLES) was false.

Question: Was (100/(exposedAreas+1)) meant instead?

This is line 12135 today on the dev branch since this file has been updated since 0.3.0.7
```
java.lang.ArithmeticException: / by zero
        at com.lilithsthrone.game.character.effects.StatusEffect.getExposedStatus(StatusEffect.java:12130)
        at com.lilithsthrone.game.character.effects.StatusEffect$100.getSVGString(StatusEffect.java:5113)
        at com.lilithsthrone.rendering.RenderingEngine.getCharacterPanelDiv(RenderingEngine.java:2130)
        at com.lilithsthrone.rendering.RenderingEngine.renderAttributesPanelRight(RenderingEngine.java:1131)
        at com.lilithsthrone.controller.MainController.updateUI(MainController.java:2198)
        at com.lilithsthrone.game.Game.endTurn(Game.java:1626)
        at com.lilithsthrone.game.Game.endTurn(Game.java:1288)
        at com.lilithsthrone.game.Game.setContent(Game.java:1792)
        at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
        at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
        at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
        at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
        at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
        at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

**Comment by CognitiveMist** [comment]
I think arpie-steele is correct, that it should be `100/(exposedAreas+1)`, which would mean that the only case for which `Math.min` is needed is when `exposedAreas == 0`. If we're wrong, one option would be something like:

```
int size = exposedAreas <= 1 ? 50 : 100/exposedAreas;
```

**Comment by arpie-steele** [comment]
It turns out there was signs of intent to split exposed breasts status into 
1. exposed breasts for those with breast and a full-figured SVG
2.  exposed nipples/flat chest for those feminine but flat-ish.
And this was only partially implemented.

The following patch seems to address all the parts:

```diff
diff --git a/src/com/lilithsthrone/game/character/effects/StatusEffect.java b/src/com/lilithsthrone/game/character/effects/StatusEffect.java
index fc7108fa..9f43b853 100644
--- a/src/com/lilithsthrone/game/character/effects/StatusEffect.java
+++ b/src/com/lilithsthrone/game/character/effects/StatusEffect.java
@@ -5097,6 +5097,14 @@ public enum StatusEffect {
                                        new Value<Attribute, Float>(Attribute.RESISTANCE_PHYSICAL, -5f)),
                        null) {
                @Override
+               public String getName(GameCharacter target) {
+                       if ( ! target.hasBreasts() ) {
+                               return "exposed nipples";
+                       } else {
+                               return super.getName(target);
+                       }
+               }
+               @Override
                public String getDescription(GameCharacter target) {
                        if(target==null) {
                                return "";
@@ -12089,6 +12097,8 @@ public enum StatusEffect {
                
                if(owner.hasBreasts() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES)) {
                        names.add("breasts");
+               } else if ( owner.isFeminine() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES)) {
+                       names.add("nipples"); // for agreement with isExposedParts
                }
                if(owner.hasBreastsCrotch() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES_CROTCH)) {
                        names.add(UtilText.parse(owner, "[npc.crotchBoobs]"));
@@ -12116,6 +12126,7 @@ public enum StatusEffect {
 
                
                boolean breastsExposed = owner.hasBreasts() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES);
+               boolean nipplesExposed = ! breastsExposed && owner.isFeminine() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES);
                boolean crotchBoobsExposed = owner.hasBreastsCrotch() && owner.isCoverableAreaVisible(CoverableArea.NIPPLES_CROTCH);
 
                boolean anusExposed = owner.isCoverableAreaVisible(CoverableArea.ANUS);
@@ -12130,15 +12141,18 @@ public enum StatusEffect {
                } else {
                        exposedAreas+= (penisExposed?1:0) + (vaginaExposed?1:0);
                }
-               exposedAreas+= (anusExposed?1:0) + (breastsExposed?1:0) + (crotchBoobsExposed?1:0);
+               exposedAreas+= (anusExposed?1:0) + (breastsExposed || nipplesExposed?1:0) + (crotchBoobsExposed?1:0);
                
-               int size = Math.min(50, (100/exposedAreas+1));
+               int size = Math.min(50, (100/(exposedAreas+1)));
                int marginTop = (100-(exposedAreas*size))/2;
                int marginLeft = (50-size)/2;
 
                if(breastsExposed) {
                        SVGImageSB.append("<div style='width:"+size+"%;height:"+size+"%;position:absolute;left:"+marginLeft+"%;top:"+marginTop+"%;'>"+SVGImages.SVG_IMAGE_PROVIDER.getCoverableAreaBreasts()+"</div>");
                        marginTop+=size;
+               } else if ( nipplesExposed ) {
+                       SVGImageSB.append("<div style='width:"+size+"%;height:"+size+"%;position:absolute;left:"+marginLeft+"%;top:"+marginTop+"%;'>"+SVGImages.SVG_IMAGE_PROVIDER.getCoverableAreaBreastsFlat()+"</div>");
+                       marginTop+=size;
                }
                if(crotchBoobsExposed) {
                        SVGImageSB.append("<div style='width:"+size+"%;height:"+size+"%;position:absolute;left:"+marginLeft+"%;top:"+marginTop+"%;'>"+SVGImages.SVG_IMAGE_PROVIDER.getCoverableAreaBreastsCrotch()+"</div>");
@@ -12178,7 +12192,7 @@ public enum StatusEffect {
                
                int exposedAreas = (vaginaRecovering?1:0) + (anusRecovering?1:0) + (nipplesRecovering?1:0) + (nipplesCrotchRecovering?1:0) + (penileUrethraRecovering?1:0) + (vaginalUrethraRecovering?1:0);
                
-               int size = Math.min(50, (100/exposedAreas+1));
+               int size = Math.min(50, (100/(exposedAreas+1)));
                int marginTop = (100-(exposedAreas*size))/2;
                int marginLeft = (50-size)/2;
 
```

**Comment by arpie-steele** [comment]
Surefire reproduction of related issue while having ones own feminine but flat chest exposed.

This is fixed by the above suggestion.

Using debugger, set Femininity to 75, Breasts/Breast Size to 0 (Flat). Remove Top, watch map crash as your nipples are exposed, but that doesn't actually contribute to the exposed status.

java.lang.ArithmeticException: / by zero
	at com.lilithsthrone.game.character.effects.StatusEffect.getExposedStatus(StatusEffect.java:12135)
	at com.lilithsthrone.game.character.effects.StatusEffect$100.getSVGString(StatusEffect.java:5114)

**Comment by Innoxia** [comment]
I merged #1068, which was definitely one cause of this issue, but I'm not sure if it was the only one. 💦
