### ISSUE TITLE
0.3.1 (dev branch) has ConcurrentModificationException when doing initial Properties.savePropertiesAsXML()

### ISSUE THREAD

**Issue by arpie-steele** [Innoxia/liliths-throne-public#1067]
Found on Mac with both HotSpot and the Oracle 1.8.0_201.

The issue appears to be updating Main.getProperties().setValue(....) in the JavaFX thread when another thread is doing Main.getProperties().savePropertiesAsXML(...) which uses an iterator on an unsynchronized. Then you get an error log like:
```
Version: 0.3.1
Java: 1.8.0_201
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1469)
	at com.lilithsthrone.game.Properties.savePropertiesAsXML(Properties.java:222)
	at com.lilithsthrone.main.Main.main(Main.java:806)
	... 11 more
```

A terrible fix would be to fix this particular condition by gluing the utils.Units and game.Properties classes together.
```diff
@@ -17,6 +17,7 @@ import com.lilithsthrone.game.inventory.weapon.AbstractWeaponType;
 import com.lilithsthrone.game.inventory.weapon.WeaponType;
 import com.lilithsthrone.game.settings.*;
 import com.lilithsthrone.main.Main;
+import com.lilithsthrone.utils.Units;
 import org.w3c.dom.Attr;
 import org.w3c.dom.Document;
 import org.w3c.dom.Element;
@@ -217,6 +218,7 @@ public class Properties {
                        
                        
 
+                       Units.FORMATTER.updateSettings();
                        Element valuesElement = doc.createElement("propertyValues");
                        properties.appendChild(valuesElement);
                        for(PropertyValue value : values) {
```
Other allocations of responsibilities are also possible to prevent this particular collision.

Another clunky fix is to wrap both the iteration block and setValue guts in synchronized blocks to cause threads to wait for each other.

An alternate fix is less clunky, avoiding the risky iterator over the changeable Set values.
```diff
diff --git a/src/com/lilithsthrone/game/Properties.java b/src/com/lilithsthrone/game/Properties.java
index 0965ece1..a4bb0be6 100644
--- a/src/com/lilithsthrone/game/Properties.java
+++ b/src/com/lilithsthrone/game/Properties.java
@@ -219,7 +219,8 @@ public class Properties {
 
                        Element valuesElement = doc.createElement("propertyValues");
                        properties.appendChild(valuesElement);
-                       for(PropertyValue value : values) {
+                       for(PropertyValue value : PropertyValue.values()) {
+                               if(! values.contains(value)) continue;
                                CharacterUtils.createXMLElementWithValue(doc, valuesElement, "propertyValue", value.toString());
                        }
 
```

**Comment by Innoxia** [comment]
Fixed from #1071
