### ISSUE TITLE
HP/MP stuck at 1. 

### ISSUE THREAD

**Issue by erishiamu** [Innoxia/liliths-throne-public#1237]
**Describe the bug**
After levelling up while fighting during an arcane storm my HP and MP both got set to one. The base for each is 1, they list a bonus (103/159), and the total is 1. 

**Expected behavior**
I should have more health. 

**To Reproduce**
Uncertain

**Attach files**
https://postimg.cc/9r3czNxK - screenshot

**Additional information:**
 - 3.5.1
 - OS: Windows 10
 - Using .exe:

Error log:
Version: 0.3.5.1
Java: 1.8.0_172
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
lynx has no orgasm actions!!!
lynx has no orgasm actions!!!
lynx has no orgasm actions!!!
lynx has no orgasm actions!!!
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.lilithsthrone.game.dialogue.utils.ParserTarget$4.getCharacter(ParserTarget.java:127)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parseSyntaxNew(UtilText.java:6406)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:941)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:648)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:643)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:632)
	at com.lilithsthrone.game.inventory.clothing.AbstractClothingType.unequipText(AbstractClothingType.java:1457)
	at com.lilithsthrone.game.inventory.clothing.AbstractClothing.onUnequipApplyEffects(AbstractClothing.java:965)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToUnequip(CharacterInventory.java:1562)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToUnequip(CharacterInventory.java:1430)
	at com.lilithsthrone.game.character.GameCharacter.unequipClothingIntoVoid(GameCharacter.java:17109)
	at com.lilithsthrone.game.character.GameCharacter.unequipAllClothingIntoVoid(GameCharacter.java:17188)
	at com.lilithsthrone.game.inventory.clothing.AbstractOutfit.applyOutfit(AbstractOutfit.java:169)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfit(CharacterUtils.java:2179)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfits(CharacterUtils.java:2168)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfitType(CharacterUtils.java:2153)
	at com.lilithsthrone.game.character.npc.dominion.DominionAlleywayAttacker.equipClothing(DominionAlleywayAttacker.java:266)
	at com.lilithsthrone.game.Game.endTurn(Game.java:1676)
	at com.lilithsthrone.game.Game.endTurn(Game.java:1486)
	at com.lilithsthrone.game.Game.setContent(Game.java:2196)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
var timer not found...
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.lilithsthrone.game.dialogue.utils.ParserTarget$4.getCharacter(ParserTarget.java:127)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parseSyntaxNew(UtilText.java:6406)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:941)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:648)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:643)
	at com.lilithsthrone.game.dialogue.utils.UtilText.parse(UtilText.java:632)
	at com.lilithsthrone.game.inventory.clothing.AbstractClothingType.unequipText(AbstractClothingType.java:1457)
	at com.lilithsthrone.game.inventory.clothing.AbstractClothing.onUnequipApplyEffects(AbstractClothing.java:965)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToUnequip(CharacterInventory.java:1562)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToUnequip(CharacterInventory.java:1430)
	at com.lilithsthrone.game.character.GameCharacter.unequipClothingIntoVoid(GameCharacter.java:17109)
	at com.lilithsthrone.game.character.GameCharacter.unequipAllClothingIntoVoid(GameCharacter.java:17188)
	at com.lilithsthrone.game.inventory.clothing.AbstractOutfit.applyOutfit(AbstractOutfit.java:169)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfit(CharacterUtils.java:2179)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfits(CharacterUtils.java:2168)
	at com.lilithsthrone.game.character.CharacterUtils.equipClothingFromOutfitType(CharacterUtils.java:2153)
	at com.lilithsthrone.game.character.npc.dominion.DominionAlleywayAttacker.equipClothing(DominionAlleywayAttacker.java:266)
	at com.lilithsthrone.game.Game.endTurn(Game.java:1689)
	at com.lilithsthrone.game.Game.endTurn(Game.java:1486)
	at com.lilithsthrone.game.Game.setContent(Game.java:2418)
	at com.lilithsthrone.game.Game.setContent(Game.java:2482)
	at com.lilithsthrone.controller.MainController.moveTile(MainController.java:2462)
	at com.lilithsthrone.controller.MainController.moveWest(MainController.java:2486)
	at com.lilithsthrone.controller.MainController$3.handle(MainController.java:554)
	at com.lilithsthrone.controller.MainController$3.handle(MainController.java:1)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord.handleCapturingEvent(CompositeEventHandler.java:282)
	at com.sun.javafx.event.CompositeEventHandler.dispatchCapturingEvent(CompositeEventHandler.java:98)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:223)
	at com.sun.javafx.event.EventHandlerManager.dispatchCapturingEvent(EventHandlerManager.java:180)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchCapturingEvent(CompositeEventDispatcher.java:43)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:52)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$KeyHandler.process(Scene.java:3964)
	at javafx.scene.Scene$KeyHandler.access$1800(Scene.java:3910)
	at javafx.scene.Scene.impl_processKeyEvent(Scene.java:2040)
	at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2501)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$352(GlassViewEventHandler.java:248)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
	at com.sun.glass.ui.View.handleKeyEvent(View.java:546)
	at com.sun.glass.ui.View.notifyKey(View.java:966)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...
var timer not found...

**Comment by IIXEGGXII** [comment]
The cause might be because you've just exceeded your' enchantment capacity.
If you turn the setting off in the menu, then it should reset your health back to its original value.
