### ISSUE TITLE
[0.3.5.4] Missing checks for use of method GameCharacter.getMainCompanion()

### ISSUE THREAD

**Issue by Ettanin1987** [Innoxia/liliths-throne-public#1238]
In some cases GameCharacter.getMainCompanion can return NULL (especially if the player doesn't have followers) which can result in an NPE such as here:

`java.lang.NullPointerException
	at com.lilithsthrone.game.dialogue.npcDialogue.submission.TunnelAttackDialogue.applyPregnancyReactions(TunnelAttackDialogue.java:88)
	at com.lilithsthrone.game.dialogue.npcDialogue.submission.TunnelAttackDialogue.access$700(TunnelAttackDialogue.java:46)
	at com.lilithsthrone.game.dialogue.npcDialogue.submission.TunnelAttackDialogue$1$1.effects(TunnelAttackDialogue.java:240)
	at com.lilithsthrone.game.dialogue.responses.Response.applyEffects(Response.java:240)
	at com.lilithsthrone.game.Game.setContent(Game.java:2049)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)`

There are too many methods affected to list them all, but at a quick glance I see that your code quality has severely deteriorated because you have several lines copypasted in various related classes that could be unified using one method.

Furthermore, i'd recommend employing a code reviewer consultant to check for quality, maintainability and null safety issues.

**Comment by DrZed** [comment]
I can partially second this I found 6 null warnings when running inspect myself. But since I can probs do it myself, I might just do it and PR it.

**Comment by triples941** [comment]
#1231 should fix the exception in TunnelAttackDialogue

**Comment by triples941** [comment]
However, SonarQube does detect a lot of potential NPEs besides the ones that were fixed, along with other issues.

**Comment by Ettanin1987** [comment]
Should be fixed by 1231
