### ISSUE TITLE
Phone menu fails in the Shopping Arcade

### ISSUE THREAD

**Issue by zR1OQicz** [Innoxia/liliths-throne-public#1327]
**Describe the bug**
The game doesn't show the Phone menu in the Shopping Arcade. Afterwards most user input is ignored.

**Expected behavior**
The Phone menu is shown. User input is processed normally.

**To Reproduce**
1. Enter the Shopping Arcade.
2. Try to open the Phone menu. Nothing happens.
3. Try moving. Nothing happens.
4. Try opening the Inventory. This works, afterwards the game continues normally.

**Attach files**
Version: 0.3.7.3
Java: 14
Warning: Nashorn engine is planned to be removed from a future JDK release
java.lang.NullPointerException
	at com.lilithsthrone.world.WorldType$12.getCompanionSexBlockedReason(WorldType.java:363)
	at com.lilithsthrone.world.AbstractWorldType.isCompanionSexBlocked(AbstractWorldType.java:189)
	at com.lilithsthrone.game.character.GameCharacter.getSexAvailabilityBasedOnLocation(GameCharacter.java:4995)
	at com.lilithsthrone.game.dialogue.utils.PhoneDialogue$1.getResponse(PhoneDialogue.java:219)
	at com.lilithsthrone.game.Game.getResponsesDiv(Game.java:2853)
	at com.lilithsthrone.game.Game.setContent(Game.java:2613)
	at com.lilithsthrone.game.Game.setContent(Game.java:2711)
	at com.lilithsthrone.controller.MainController.openPhone(MainController.java:289)
	at com.lilithsthrone.controller.MainController.openPhone(MainController.java:267)
	at com.lilithsthrone.controller.eventListeners.buttons.ButtonJournalEventListener.handleEvent(ButtonJournalEventListener.java:17)
	at javafx.web/com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at javafx.web/com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at javafx.web/com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:809)
	at javafx.web/javafx.scene.web.WebView.processMouseEvent(WebView.java:1009)
	at javafx.web/javafx.scene.web.WebView.lambda$registerEventHandlers$3(WebView.java:1132)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Scene.java:3890)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Scene.java:1885)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(View.java:556)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(View.java:942)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:832)

... several repetitions of the same stack trace removed

**Additional information:**
 - Game version 0.3.7.3
 - OS: [e.g. Windows 10]
 - self-compiled from github source, commit: 03ffe15f7bb79c06f83a88bdff43acc84c847f4f
 - java --version
   openjdk 14 2020-03-17
   OpenJDK Runtime Environment (build 14+36-suse-1.1-x8664)
   OpenJDK 64-Bit Server VM (build 14+36-suse-1.1-x8664, mixed mode)

**Comment by Innoxia** [comment]
This will be fixed in the next update, thank you for the report!
