### ISSUE TITLE
Combat victory screen breaks after winning against imp gangs en route to the final fortress in Submission

### ISSUE THREAD

**Issue by Vittaminn** [Innoxia/liliths-throne-public#1463]
**Describe the bug**
After encountering, fighting, and winning against a gang of imps on the way to the final fortress in Submission, when you click on the "Victory" button, the screen re-displays combat options instead of the post-combat screen. None of the buttons displayed are responsive and most of the other UI elements become completely unresponsive. An error.log file is generated in the /data folder, describing a null pointer exception (java.lang.NullPointerException). Closing the game, opening it back up, and reloading from a save then trying again leads to this bug over and over again. At this point, I'm betting the only way around it is to get lucky and NOT encounter an imp gang on the way to the fortress. I did not see this issue when fighting and winning against the imp gangs from any of the three other fortresses, if that helps.

**Expected behavior**
Clicking the "Victory" button normally progresses the game to the post-combat screen. Instead, this bug causes the game to re-display combat options and most of the UI breaks.

**To Reproduce**
I encountered this error while progressing through the quest where you have to take down the Dark Siren. Prior to finding this bug, I got a hold of all three keys (without any problems) and was on my way to the final fortress. I encountered an imp gang like normal, but upon beating them I ran into this bug.

**Attach files**
Please either attach a copy of your error.log (in the LilithsThrone/data directory), or copy & paste the contents to the end of this bug report.

**Additional information:**
 - Game Version: 0.3.13
 - OS: Windows 10
 - Using the .exe version
------------------------------------------------------------------------------------------------------------------------------------
error.log text:

Version: 0.3.13
Java: 1.8.0_172
java.lang.NullPointerException
	at com.lilithsthrone.game.character.npc.submission.ImpAttacker.getFeminineEffects(ImpAttacker.java:600)
	at com.lilithsthrone.game.character.npc.submission.ImpAttacker.generateTransformativePotion(ImpAttacker.java:402)
	at com.lilithsthrone.game.character.npc.submission.ImpAttacker.endCombat(ImpAttacker.java:317)
	at com.lilithsthrone.game.combat.Combat$4$3.effects(Combat.java:780)
	at com.lilithsthrone.game.dialogue.responses.Response.applyEffects(Response.java:239)
	at com.lilithsthrone.game.Game.setContent(Game.java:2481)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Unknown Source)

**Comment by AceXP** [comment]
From the stack trace, it looks like there is an issue when determining the subspecies (or it's related transformative item) of the main character. No telling what could be the issue without further information. Would it be possible to upload a save so it can be investigated further?

**Comment by Vittaminn** [comment]
Sure thing! Github's not letting me upload just the .xml, so I just quickly used 7-Zip to throw it in a zip file. If you need anything else from me, I'm more than happy to provide more info whenever.
[Save1.zip](https://github.com/Innoxia/liliths-throne-public/files/5747958/Save1.zip)

**Comment by AceXP** [comment]
Found out what the problem is, I'll see if I can have it fixed.

**Comment by Vittaminn** [comment]
Oh cool, thanks for looking into it!

**Comment by AceXP** [comment]
This should now work properly in version 0.3.20. Could you check it and close this issue?

`Fixed softlock at the end of combat when fighting imps in Submission. (by AceXP)`

**Comment by Vittaminn** [comment]
Ah, my bad. Yes it works fine now. Appreciated!
