### ISSUE TITLE
Cannot launch on Linux with OpenJDK and OpenJFX

### ISSUE THREAD

**Issue by Rawrior** [Innoxia/liliths-throne-public#1546]
**Describe the bug**
Launching on linux with openjdk and openjfx produces an error that says  
```
File 'res/patchnotes/toc.xml' could not be loaded!
Printing to error.log
```

**Expected behavior**
Game should launch.

**To Reproduce**
1. Use Arch or an Arch-derivative distribution.
2. Install openjfx with `pacman -S java-openjfx`
3. Copy javafx .jar files from `usr/lib/jvm/java-15-openjdk/lib` to `~/javafx`
4. Try to launch with command `java -jar --module-path ~/javafx --add-modules javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web LilithsThrone_0_4.jar`

**Attach files**
error.log output:
```
Game Version: 0.4
Java: 15.0.2
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1071)
Caused by: java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/NashornScriptEngineFactory
	at com.lilithsthrone.game.dialogue.utils.UtilText.<clinit>(UtilText.java:221)
	at com.lilithsthrone.game.dialogue.DialogueNode.loadDialogueNodesFromFile(DialogueNode.java:118)
	at com.lilithsthrone.game.dialogue.DialogueManager.<clinit>(DialogueManager.java:92)
	at com.lilithsthrone.world.places.AbstractPlaceType.<init>(AbstractPlaceType.java:225)
	at com.lilithsthrone.world.places.PlaceType$202.<init>(PlaceType.java:5739)
	at com.lilithsthrone.world.places.PlaceType.<clinit>(PlaceType.java:5739)
	at com.lilithsthrone.world.WorldType.<clinit>(WorldType.java:35)
	at com.lilithsthrone.game.character.race.Subspecies.<clinit>(Subspecies.java:167)
	at com.lilithsthrone.game.Properties.<init>(Properties.java:237)
	at com.lilithsthrone.main.Main.main(Main.java:670)
	... 11 more
Caused by: java.lang.ClassNotFoundException: jdk.nashorn.api.scripting.NashornScriptEngineFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
Exception running application com.lilithsthrone.main.Main
```

**Additional information:**
 - Game version: 4.0
 - OS: Manjaro Linux 5.12.0-1
 - Using .jar or .exe: .jar

**Comment by AceXP** [comment]
The error with the toc file not loading is a known bug.

The game is searching in res/patchnotes/, but the folder is called patchNotes. If you change that folder name it will work.

The ClassNotFound exception is because LT uses the Nashorn scripting engine, and that is removed in Java 15 and later. You will have to use an earlier version of Java to fix that.

**Comment by Rawrior** [comment]
> The error with the toc file not loading is a known bug.
> 
> The game is searching in res/patchnotes/, but the folder is called patchNotes. If you change that folder name it will work.  

Thanks, that helps :)

> The ClassNotFound exception is because LT uses the Nashorn scripting engine, and that is removed in Java 15 and later. You will have to use an earlier version of Java to fix that.  

I changed to openjdk 11 and tried to run the same command, but now I'm getting a different error. Googling around gave various obscure fixes (including installing openjfx) that didn't work. Do you happen to know anything about this?

```
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:244)
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.base/java.lang.Thread.run(Thread.java:829)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: No toolkit found
	at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:273)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	... 5 more
```

**Comment by Rawrior** [comment]
I poked around a bit more. Copying `libprism_es2.so`, `libprism_sw.so`, `libglass.so`, and `libglassgtk3.so` to the `~/javafx` folder helped. Now it looks like there's a problem with loading fonts? error.log below:

```
Game Version: 0.4
Java: 11.0.11
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
	at javafx.graphics/com.sun.javafx.font.PrismFontLoader.loadFont(PrismFontLoader.java:119)
	at javafx.graphics/javafx.scene.text.Font.loadFontInternal(Font.java:486)
	at javafx.graphics/javafx.scene.text.Font.loadFont(Font.java:405)
	at com.lilithsthrone.main.Main.loadFonts(Main.java:549)
	at com.lilithsthrone.main.Main.start(Main.java:460)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 1 more
Exception running application com.lilithsthrone.main.Main
```

**Comment by AceXP** [comment]
Have a look here maybe? Looks like the same issue.

https://stackoverflow.com/questions/14977546/javafx-nullpointerexception-on-startup

**Comment by Rawrior** [comment]
The user-submitted workaround doesn't work, since I already have a `/usr/share/fonts/TTF/` with several TTF fonts, and the error still persists.

**Comment by Rawrior** [comment]
I got it fixed! If you're reading this and you have the same problem on an arch-derivative Linux, try these steps:

1. Install openjre11 with `pacman -S jre11-openjdk`
2. Install openjfx11 with `pacman -S java11-openjfx`
3. Set your default jre to java 11 with `sudo archlinux-java set java-11-openjdk`
4. Run Lilith's Throne with `java -jar --module-path /usr/lib/jvm/java-11-openjfx/lib/ --add-modules javafx.fxml,javafx.web LilithsThrone_0_4.jar` from inside the Lilith's Throne folder.

This got me to the title menu screen, at least. I'll be on the lookout for the need to add more modules in the `--add-modules` argument. The set of possibilities include javafx.{base, controls, fxml, graphics, media, swing, web}, but I don't currently know which are required to make the game work fully.
