### ISSUE TITLE
"Stop Sex" Does not return to any menu

### ISSUE THREAD

**Issue by tyr4n02r** [Innoxia/liliths-throne-public#310]
Stop sex (having tried Multiple, Slave, Rape and Pix) does not return me to the previous menu (World Map, post-fight, etc.) Issue as of 2.2. Also on .jar if that helps anything.

**Comment by A-Master-of-Puppets** [comment]
Can you attach your error log?

**Comment by tyr4n02r** [comment]
any instructions no how to do that? Sorry not a programmer, was just reporting the error.

**Comment by A-Master-of-Puppets** [comment]
Look for the error log file in the data folder, and attach it like it says below the box where you type in your message here.

**Comment by tyr4n02r** [comment]
/Users/Admin/Desktop/Sylenth1 Soundbanks/Fenoxo/Lilith's Throne/data/error.log

**Comment by tyr4n02r** [comment]
Take 2...

**Comment by tyr4n02r** [comment]
Alright, seriously...
Its not uploading to the site unless you guys see something on here that I dont.

**Comment by tyr4n02r** [comment]
Yea. The file isnt upload ing either... 8 attempts with different browsers...

**Comment by tyr4n02r** [comment]
Ok so since it doesnt seem that big ill post the code. Sorry for the dump.

java.lang.IllegalArgumentException: The supplied clothing cannot be displaced in this manner!
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToBeDisplaced(CharacterInventory.java:1288)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToBeDisplaced(CharacterInventory.java:1217)
	at com.lilithsthrone.game.character.GameCharacter.isAbleToBeDisplaced(GameCharacter.java:9924)
	at com.lilithsthrone.game.sex.Sex.endSex(Sex.java:479)
	at com.lilithsthrone.game.sex.Sex.access$7(Sex.java:462)
	at com.lilithsthrone.game.sex.Sex$1$1.effects(Sex.java:1049)
	at com.lilithsthrone.game.dialogue.responses.Response.applyEffects(Response.java:174)
	at com.lilithsthrone.game.Game.setContent(Game.java:1185)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
java.lang.IllegalArgumentException: The supplied clothing cannot be displaced in this manner!
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToBeDisplaced(CharacterInventory.java:1288)
	at com.lilithsthrone.game.inventory.CharacterInventory.isAbleToBeDisplaced(CharacterInventory.java:1217)
	at com.lilithsthrone.game.character.GameCharacter.isAbleToBeDisplaced(GameCharacter.java:9924)
	at com.lilithsthrone.game.sex.Sex.endSex(Sex.java:479)
	at com.lilithsthrone.game.sex.Sex.access$7(Sex.java:462)
	at com.lilithsthrone.game.sex.Sex$1$1.effects(Sex.java:1049)
	at com.lilithsthrone.game.dialogue.responses.Response.applyEffects(Response.java:174)
	at com.lilithsthrone.game.Game.setContent(Game.java:1185)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by A-Master-of-Puppets** [comment]
OK, quick check: are you wearing a kanzashi? Can you try removing that before sex and see what happens?

**Comment by tyr4n02r** [comment]
No Im not, however this comment gave me the idea to check other clothes.
- Unequiping overtorso clothes before sex didnt work.
- Neither did "displace all + them" before sex.
- Neither did naked battle -> Sex
- I also tried sex at a different starting eagerness.

**Comment by bicobus** [comment]
Could you share the save file for which the problem occurs?

**Comment by tyr4n02r** [comment]
[Archive.zip](https://github.com/Innoxia/liliths-throne-public/files/1876393/Archive.zip)
Hey, cheated the upload system! Thats the error log and save file.

**Comment by A-Master-of-Puppets** [comment]
Right, it's the bandanna. You had it pulled up, and when the game was changed so bandannas are pulled _down_ instead, it broke things. Remove that and things will be fine. I'll work out a fix for that now.

**Comment by tyr4n02r** [comment]
Yep it worked. Thanks all.

**Comment by Innoxia** [comment]
This should be fixed now, thanks to the fix #313 from @A-Master-of-Puppets. Thank you for the report!
