### ISSUE TITLE
Companions are exported in character export and cause stacktraces that they can't be found via getNPCById upon import

### ISSUE THREAD

**Issue by Pimvgd** [Innoxia/liliths-throne-public#468]
See attached export;

[Tamitha_day3.zip](https://github.com/Innoxia/liliths-throne-public/files/1997014/Tamitha_day3.zip)

Fix needs to A) not export companions anymore and B) stop trying to import companions to preserve compatibility with old versions

**Comment by Pimvgd** [comment]
The stacktrace:
```
!WARNING! getNPC(12,Elemental) is returning null!
!WARNING! getNPC(12,Elemental) is returning null!
java.lang.NullPointerException
	at com.lilithsthrone.game.character.effects.StatusEffect$170.isConditionsMet(StatusEffect.java:7065)
	at com.lilithsthrone.game.character.GameCharacter.calculateStatusEffects(GameCharacter.java:3856)
	at com.lilithsthrone.main.Main.importCharacter(Main.java:829)
	at com.lilithsthrone.controller.MainControllerInitMethod.lambda$267(MainControllerInitMethod.java:4667)
	at com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(EventListenerImpl.java:129)
	at com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at com.sun.webkit.WebPage.dispatchMouseEvent(WebPage.java:807)
	at javafx.scene.web.WebView.processMouseEvent(WebView.java:1045)
	at javafx.scene.web.WebView.lambda$registerEventHandlers$32(WebView.java:1168)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Innoxia** [comment]
I fixed this by adding a couple more values to the `CharacterImportSetting` Enum (NO_COMPANIONS and NO_ELEMENTAL).

The `SlaveImport` class now calls these in the `loadFromXML` method to stop it from loading in companions and elementals.
