### ISSUE TITLE
Exception when trying to change position when having sex with a slave in the stocks

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#823]
**Version** : 0.2.7.8
**Date** : 28 June 2018

Error.log after trying to select "Perform oral" : 

`BlockedParts loading failed. Code 1 elbow-length latex glove
AbstractClothingType loading failed. Cause: 'blockedPartsList' element unable to be parsed.
java.lang.NullPointerException
	at com.lilithsthrone.game.sex.Sex.updateAvailableActions(Sex.java:3311)
	at com.lilithsthrone.game.sex.Sex.setSexManager(Sex.java:3271)
	at com.lilithsthrone.game.sex.sexActions.universal.StocksSex$2.applyEffects(StocksSex.java:113)
	at com.lilithsthrone.game.sex.sexActions.SexActionInterface.baseEffects(SexActionInterface.java:186)
	at com.lilithsthrone.game.sex.Sex.endSexTurn(Sex.java:1230)
	at com.lilithsthrone.game.sex.sexActions.SexActionInterface$1.effects(SexActionInterface.java:580)
	at com.lilithsthrone.game.dialogue.responses.Response.applyEffects(Response.java:184)
	at com.lilithsthrone.game.Game.setContent(Game.java:1512)
	at com.lilithsthrone.controller.eventListeners.SetContentEventListener.handleEvent(SetContentEventListener.java:36)
	at javafx.web/com.sun.webkit.dom.EventListenerImpl.fwkHandleEvent(Unknown Source)
	at javafx.web/com.sun.webkit.WebPage.twkProcessMouseEvent(Native Method)
	at javafx.web/com.sun.webkit.WebPage.dispatchMouseEvent(Unknown Source)
	at javafx.web/javafx.scene.web.WebView.processMouseEvent(Unknown Source)
	at javafx.web/javafx.scene.web.WebView.lambda$registerEventHandlers$3(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$MouseHandler.access$1300(Unknown Source)
	at javafx.graphics/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
`

Save : 

[AutoSave_Opala.zip](https://github.com/Innoxia/liliths-throne-public/files/2144858/AutoSave_Opala.zip)

**Comment by Nenoxx** [comment]
Note : related to #815

**Comment by Nenoxx** [comment]
**Fixed 0.2.8**
